export const SET_AUTH = 'SET_AUTH';
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_LOADING = 'SET_LOADING';

export const ADD_REQUEST_TO_HISTORY = 'ADD_REQUEST_TO_HISTORY';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';
export const USE_RESPONSE_FROM_HISTORY = 'USE_RESPONSE_FROM_HISTORY';
export const SET_RESPONSE_ERROR = 'SET_RESPONSE_ERROR';

export const SET_REQUEST = 'SET_REQUEST';
export const SET_RESPONSE = 'SET_RESPONSE';
export const SELECT_REQUEST = 'SELECT_REQUEST';

export const CLEAR_HISTORY = 'CLEAR_HISTORY';
